Document: php-yaml
Title: Debian php-yaml Manual
Author: <insert document author here>
Abstract: This manual describes what php-yaml is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/php-yaml/php-yaml.sgml.gz

Format: postscript
Files: /usr/share/doc/php-yaml/php-yaml.ps.gz

Format: text
Files: /usr/share/doc/php-yaml/php-yaml.text.gz

Format: HTML
Index: /usr/share/doc/php-yaml/html/index.html
Files: /usr/share/doc/php-yaml/html/*.html
